sudo: false

language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "6"

os:
- osx
- linux

install:
  - travis_retry npm install

script:
  - uname -a
  - node --version
  - npm --version
  - npm run clean
  - npm run ci-lint
  - npm run ci-test

after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
